import type { Locale } from "@/lib/physics";

const th = {
  docTitle: "ทุเรียนของนิวตัน",
  nav: {
    brand: "ทุเรียนของนิวตัน",
    aria: "หัวข้ออินโฟกราฟิก",
    physics: "ฟิสิกส์",
    lab: "ทดลอง",
    timeline: "ไทม์ไลน์",
    map: "ภูมิศาสตร์",
    after: "สิ่งที่ค้นพบ",
  },
  lang: { group: "ภาษา", th: "TH", en: "EN" },
  hero: {
    alt: "ภาพวาดสีน้ำมัน นิวตันนั่งใต้ต้นไม้ขณะทุเรียนหนามคมกำลังตกใส่หัว",
    kicker: "WHAT IF / 1666",
    title: "ถ้าทุเรียนตกใส่หัวนิวตัน",
    lede: "แอปเปิ้ลให้ insight ทุเรียนให้ CT scan — อินโฟกราฟิกสมมติฐานทางฟิสิกส์ ว่าประวัติศาสตร์วิทยาศาสตร์จะพังแค่ไหน ถ้าลูกที่ตกไม่ใช่ผลไม้ที่ถูกออกแบบมาสำหรับหัวคน",
    cta: "เลื่อนดูหลักฐาน",
  },
  compare: {
    kicker: "ฟิสิกส์ไม่เมตตา",
    title: "ความเร็วเท่ากัน พลังงานคนละโลก",
    bodyBefore: "ตกจากความสูงเดียวกัน ความเร่ง",
    bodyAfter:
      "เท่ากัน ความเร็วตอนถึงหัวจึงใกล้เคียงกันราว 9 เมตร/วินาที — ที่ต่างคือมวล และหนามที่เปลี่ยนแรงให้เป็นความดัน",
    appleKicker: "แอปเปิ้ล",
    appleTitle: "Insight",
    appleAlt: "ภาพนิ่งสีน้ำมันของแอปเปิ้ลลูกเดียวบนโต๊ะไม้",
    appleBack: "มวลน้อย แรงกระจาย นั่งคิดต่อได้ — จักรวาลได้สมการ",
    durianKicker: "ทุเรียน",
    durianTitle: "CT scan",
    durianAlt: "ภาพนิ่งสีน้ำมันของทุเรียนทั้งลูกบนโต๊ะไม้",
    durianBack: "มวลกว่า 14 เท่า หนามกระจุกแรง — จักรวาลได้ใบรับรองแพทย์",
    mass: "มวล",
    energyAt4: "พลังงานที่ 4 ม.",
    tapHint: "แตะการ์ดเพื่อพลิก",
    weigh: "ชั่งดู",
    weighed: "ทุเรียนหนักกว่า 14 เท่า",
    tableCaption: "เปรียบเทียบแอปเปิ้ลกับทุเรียนเมื่อตกจาก 4 เมตร",
    colVar: "ตัวแปร",
    rows: [
      { label: "มวล", apple: "0.18 กก.", durian: "2.5 กก." },
      { label: "พลังงานที่ 4 ม.", apple: "7 จูล", durian: "98 จูล" },
      { label: "พื้นผิว", apple: "กลม กระจายแรง", durian: "หนาม กระจุกแรง" },
      { label: "ผลต่อหัว", apple: "ช็อค แล้วนั่งคิดต่อ", durian: "เลิกคิดเรื่องแรงโน้มถ่วง" },
    ],
    footnote:
      "ที่ความสูง 4 เมตร ทุเรียนมีพลังงานจลน์มากกว่าแอปเปิ้ลราว 14 เท่า กะโหลกศตวรรษที่ 17 ไม่ได้ออกแบบมาสำหรับของแบบนี้",
  },
  lab: {
    kicker: "ห้องทดลองสวน Woolsthorpe",
    title: "ลากความสูง แล้วดูว่าหัวไหวหรือยัง",
    bodyBefore: "สูตรเดียวกับที่นิวตันจะได้เขียน ถ้ายังสติอยู่:",
    bodyAfter: "",
    dropHeight: "ความสูงที่ลูกไม้ตก",
    meters: "เมตร",
    sameSpeed: "ความเร็วเท่ากัน",
    sliderAria: "ปรับความสูงจาก 1 ถึง 12 เมตร",
    markBush: "1 ม. พุ่มไม้",
    markApple: "4 ม. ต้นแอปเปิ้ล",
    markDurian: "12 ม. ต้นทุเรียน",
    apple: "แอปเปิ้ล",
    durian: "ทุเรียน",
    massApple: "180 กรัม",
    massDurian: "2.5 กิโลกรัม",
    joules: "จูล",
    footnoteBefore: "ที่ความสูงนี้ ทุเรียนเทียบเท่าแอปเปิ้ล",
    footnoteUnit: "ลูก",
    footnoteAfter:
      "ตกพร้อมกัน — ความเร็วไม่เปลี่ยนตามมวล นั่นคือบทเรียนที่แอปเปิ้ลเคยสอน แต่ทุเรียนจะสอนด้วยวิธีที่แรงกว่า",
    choose: "เลือกผลไม้",
    drop: "ปล่อยลูก",
    dropping: "กำลังตก…",
    reset: "ยกขึ้นใหม่",
    target: "หัวนิวตัน",
    impact: "กระแทก",
  },
  risk: {
    shock: { label: "ช็อค นิดหน่อย", hint: "นั่งคิดต่อได้" },
    bruise: { label: "ฟกช้ำ", hint: "บวม ปวด วิกหลุด" },
    fracture: { label: "เสี่ยงกะโหลก", hint: "แรงกระจุกที่หนาม" },
    critical: { label: "อันตรายร้ายแรง", hint: "เลิกคิดเรื่องแรงโน้มถ่วง" },
  },
  timeline: {
    kicker: "ไทม์ไลน์ประวัติศาสตร์พัง",
    title: "ปีแห่งปาฏิหาริย์ ที่ไม่มีปาฏิหาริย์",
    hint: "แตะปีเพื่อเปิดบันทึก",
    events: [
      {
        year: "1666",
        title: "Annus Mirabilis กลายเป็นปีแห่งกลิ่น",
        body: "ทุเรียนตก นิวตันหมดสติข้างต้นไม้ แกะไม่ทันเพราะหนามปักวิก แม่คิดว่าลูกชายถูกสาป",
      },
      {
        year: "1666",
        title: "Woolsthorpe ไร้ผู้อยู่อาศัย",
        body: "กฎการอนุรักษ์กลิ่นทำงานทันที แกะกับแมวหนี คฤหาสน์ทั้งหลังกลายเป็นเขตห้ามเข้า",
      },
      {
        year: "1687",
        title: "Principia ไม่ถูกเขียน",
        body: "ไม่มีกฎแรงโน้มถ่วงสากลในรูปที่เราคุ้น ฮุกอาจได้เครดิต — หรือยุโรปต้องรออีกคน",
      },
      {
        year: "1716",
        title: "ไลบ์นิซชนะแบบ walkover",
        body: "สงครามแคลคูลัสจบก่อนเริ่ม เพราะอีกฝ่ายอยู่ในบันทึกแพทย์ ไม่ใช่ราชสมาคม",
      },
      {
        year: "วันนี้",
        title: "หมวกกันน็อกมาก่อนกลศาสตร์",
        body: "อังกฤษอาจได้หมวกนิรภัยก่อนได้กฎข้อที่ 3 และดวงจันทร์ยังตกไม่ถึงโลกโดยไม่มีใครอธิบาย",
      },
    ],
  },
  geo: {
    kicker: "ปัญหาที่ใหญ่กว่าหนาม",
    title: "ทุเรียนไม่มีทางอยู่ที่นั่น",
    body: "ถ้าต้นทุเรียนขึ้นที่สวนนิวตันจริง จักรวาลนี้ต้องมีคนขนมันมาโดยเจตนา ซึ่งแย่กว่าโดนลูกไม้ เพราะแปลว่ามีคนอยากให้เรื่องนี้เกิด",
    facts: [
      {
        kicker: "ทุเรียน",
        title: "ไม้เขตร้อน",
        body: "โตได้ที่ 24–30°C ความชื้นสูง ฝนชุก — สวนในเอเชียตะวันออกเฉียงใต้ ไม่ใช่ลินคอล์นเชียร์",
      },
      {
        kicker: "อังกฤษ 1666",
        title: "Little Ice Age",
        body: "ยุคที่แม่น้ำเทมส์แข็งเป็นน้ำแข็ง ปลูกแอปเปิ้ลยังฉ่ำ ต้นทุเรียนคือความผิดปกติระดับพระเจ้าล้อเล่น",
      },
      {
        kicker: "ระยะทาง",
        title: "ราว 10,000 กม.",
        body: "จากเอเชียตะวันออกเฉียงใต้ถึง Woolsthorpe ไม่มีเส้นทางค้าทุเรียนในศตวรรษที่ 17",
      },
    ],
    from: "เอเชียตะวันออกเฉียงใต้",
    to: "Woolsthorpe",
    voyage: "ลากเส้นทางที่เป็นไปไม่ได้",
    voyaging: "กำลังข้ามทวีป…",
    again: "ลากอีกครั้ง",
    km: "กม.",
    mapAlt: "แผนที่โลกสไตล์ศตวรรษที่ 17 จากหมู่เกาะอินเดียตะวันออกถึงอังกฤษ",
    legend: "เส้นทางเดินเรือบริษัทอินเดียตะวันออก ที่ทุเรียนไม่มีทางรอดมาได้",
    impossible: "เป็นไปไม่ได้",
    impossibleNote: "ทุเรียนเน่าก่อนพ้นเส้นศูนย์สูตร — ศตวรรษที่ 17 ไม่มีเส้นทางค้าแบบนี้",
    stops: {
      origin: "เอเชียตะวันออกเฉียงใต้",
      cape: "แหลมกู๊ดโฮป",
      dest: "Woolsthorpe",
    },
    stopNotes: {
      origin: "ต้นกำเนิด",
      cape: "อ้อมแอฟริกา",
      dest: "ปลายทางที่ไม่มี",
    },
  },
  disc: {
    kicker: "สิ่งที่อาจค้นพบแทน",
    title: "ถ้ายังไม่ตาย เขาจะได้กฎชุดใหม่",
    hint: "แตะเพื่อเปิดกฎ",
    finds: [
      {
        no: "I",
        title: "กฎการอนุรักษ์กลิ่น",
        body: "กลิ่นทุเรียนไม่หาย แค่ย้ายห้อง และกระจายด้วยระยะทางยกกำลังสองเหมือนแรงที่เขาคิดไม่ทัน",
        back: "I ∝ 1 / r² — ปิดประตูแล้วกลิ่นยังอยู่",
      },
      {
        no: "II",
        title: "แรงกระแทกเฉพาะจุด",
        body: "หนามเปลี่ยนแรงให้เป็นความดัน รากฐานกลศาสตร์การแตกหัก ก่อนใครหลายร้อยปี",
        back: "P = F / A — A ของหนามเล็กจนหัวไม่ควรทดลอง",
      },
      {
        no: "III",
        title: "หมวกกันน็อก",
        body: "สิทธิบัตรแรกของราชสมาคม ไม่ใช่กล้องโทรทรรศน์สะท้อนแสง แต่เป็นสิ่งที่ควรมีตั้งแต่ต้น",
        back: "a = 0 ดีกว่า a = g เมื่อวัตถุมีหนาม",
      },
      {
        no: "IV",
        title: "แรงผลักสากล",
        body: "ทุกคนในรัศมี 50 เมตรเคลื่อนที่ออกจากจุดกำเนิดกลิ่น — ปฏิกิริยาที่เท่ากับแรงกระทำจริง",
        back: "F_smell = −k / r² — ทุกคนถอยเท่า ๆ กัน",
      },
    ],
  },
  close: {
    altFall: "ภาพวาดสีน้ำมัน นิวตันนั่งใต้ต้นไม้ขณะทุเรียนกำลังตกใส่หัว",
    altAfter: "ภาพวาดสีน้ำมัน นิวตันนั่งมึนหลังโดนทุเรียน ผลแตกและกลิ่นคลุ้งสวนอังกฤษ",
    before: "ก่อนตก",
    after: "หลังตก",
    drag: "ลากเพื่อเทียบก่อนและหลัง",
    quote:
      "แอปเปิ้ลทำให้มนุษย์เข้าใจว่าดวงจันทร์ตกไม่ถึงโลก ทุเรียนทำให้มนุษย์เข้าใจว่าบางอย่างไม่ควรตกใส่หัวใครเลย",
    lede: "แรงโน้มถ่วงยังทำงานเหมือนเดิม แอปเปิ้ลกับทุเรียนตกด้วยความเร่ง g เท่ากัน ต่างกันแค่แอปเปิ้ลให้จักรวาล ทุเรียนให้ใบรับรองแพทย์",
    note: "เรื่องแอปเปิ้ลเป็นตำนานที่เล่าต่อจากนิวตัน ไม่ใช่บันทึกการทดลอง ตัวเลขในหน้านี้เป็นการประมาณจากมวลลูกไม้ทั่วไป ความสูง 4 เมตร และเกณฑ์พลังงานกระแทกอย่างหยาบ ไม่ใช่รายงานการแพทย์",
  },
};

type Copy = typeof th;

const en: Copy = {
  docTitle: "Newton's Durian",
  nav: {
    brand: "Newton's Durian",
    aria: "Infographic sections",
    physics: "Physics",
    lab: "Lab",
    timeline: "Timeline",
    map: "Geography",
    after: "Discoveries",
  },
  lang: { group: "Language", th: "TH", en: "EN" },
  hero: {
    alt: "Oil painting of Newton under a tree as a spiky durian falls toward his head",
    kicker: "WHAT IF / 1666",
    title: "If a durian hit Newton",
    lede: "An apple gives you insight. A durian gives you a CT scan — a physics thought experiment on how badly science history breaks if the fruit was never designed for a human skull.",
    cta: "See the evidence",
  },
  compare: {
    kicker: "Physics is not kind",
    title: "Same speed. Different worlds of energy.",
    bodyBefore: "Dropped from the same height, acceleration",
    bodyAfter:
      "is the same, so they hit the head at about 9 m/s. What changes is mass — and spikes that turn force into pressure.",
    appleKicker: "Apple",
    appleTitle: "Insight",
    appleAlt: "Baroque still life of a single apple on a wooden table",
    appleBack: "Little mass, spread-out force. He keeps thinking. The universe gets an equation.",
    durianKicker: "Durian",
    durianTitle: "CT scan",
    durianAlt: "Baroque still life of a whole durian on a wooden table",
    durianBack: "Over 14× the mass, force on a thorn tip. The universe gets a medical report.",
    mass: "Mass",
    energyAt4: "Energy at 4 m",
    tapHint: "Tap a card to flip it",
    weigh: "Weigh them",
    weighed: "The durian is 14× heavier",
    tableCaption: "Apple versus durian dropped from 4 metres",
    colVar: "Variable",
    rows: [
      { label: "Mass", apple: "0.18 kg", durian: "2.5 kg" },
      { label: "Energy at 4 m", apple: "7 J", durian: "98 J" },
      { label: "Surface", apple: "Round, spreads force", durian: "Spikes, concentrates it" },
      { label: "To the head", apple: "A jolt, then more thinking", durian: "Gravity can wait" },
    ],
    footnote:
      "At 4 metres a durian carries about 14× the kinetic energy of an apple. A 17th-century skull was not specced for this.",
  },
  lab: {
    kicker: "Woolsthorpe garden laboratory",
    title: "Drag the height. See if the head survives.",
    bodyBefore: "The same formulae Newton might have written, had he stayed conscious:",
    bodyAfter: "",
    dropHeight: "Drop height",
    meters: "metres",
    sameSpeed: "Same speed",
    sliderAria: "Set height from 1 to 12 metres",
    markBush: "1 m shrub",
    markApple: "4 m apple tree",
    markDurian: "12 m durian tree",
    apple: "Apple",
    durian: "Durian",
    massApple: "180 g",
    massDurian: "2.5 kg",
    joules: "J",
    footnoteBefore: "At this height the durian equals",
    footnoteUnit: "apples",
    footnoteAfter:
      "falling at once. Speed does not care about mass — that is the apple’s lesson. The durian teaches it harder.",
    choose: "Choose a fruit",
    drop: "Drop it",
    dropping: "Falling…",
    reset: "Reset",
    target: "Newton’s head",
    impact: "Impact",
  },
  risk: {
    shock: { label: "Mild jolt", hint: "He can keep thinking" },
    bruise: { label: "Bruise", hint: "Swelling, pain, wig askew" },
    fracture: { label: "Skull at risk", hint: "Force on a thorn tip" },
    critical: { label: "Severe", hint: "Gravity will have to wait" },
  },
  timeline: {
    kicker: "A wrecked history",
    title: "The year of wonders, without the wonders",
    hint: "Tap a year to open the record",
    events: [
      {
        year: "1666",
        title: "Annus Mirabilis becomes a year of smell",
        body: "The durian falls. Newton blacks out under the tree. The thorns pin his wig. His mother assumes a curse.",
      },
      {
        year: "1666",
        title: "Woolsthorpe is abandoned",
        body: "Conservation of odour kicks in at once. Sheep and cats flee. The manor becomes a no-go zone.",
      },
      {
        year: "1687",
        title: "The Principia is never written",
        body: "No familiar law of universal gravitation. Hooke might take the credit — or Europe waits for someone else.",
      },
      {
        year: "1716",
        title: "Leibniz wins by walkover",
        body: "The calculus war ends before it starts. The other party is in a medical file, not the Royal Society.",
      },
      {
        year: "Today",
        title: "Helmets before mechanics",
        body: "England might invent hard hats before the third law, and the Moon still fails to fall with no one to explain why.",
      },
    ],
  },
  geo: {
    kicker: "A problem bigger than the thorns",
    title: "A durian had no business being there",
    body: "If a durian tree really stood in Newton’s garden, someone in this universe shipped it on purpose — which is worse than the fruit, because it means the blow was intended.",
    facts: [
      {
        kicker: "Durian",
        title: "A tropical tree",
        body: "It wants 24–30°C, wet air, heavy rain — Southeast Asian orchards, not Lincolnshire.",
      },
      {
        kicker: "England, 1666",
        title: "Little Ice Age",
        body: "The Thames froze solid. Apples already struggled. A durian tree is a cosmic prank.",
      },
      {
        kicker: "Distance",
        title: "About 10,000 km",
        body: "From Southeast Asia to Woolsthorpe there was no durian trade in the 17th century.",
      },
    ],
    from: "Southeast Asia",
    to: "Woolsthorpe",
    voyage: "Trace the impossible voyage",
    voyaging: "Crossing hemispheres…",
    again: "Trace again",
    km: "km",
    mapAlt: "A 17th-century world map from the East Indies to England",
    legend: "The East India sea route a durian could never survive",
    impossible: "Impossible",
    impossibleNote: "The fruit would rot before the equator. No 17th-century trade carried durian.",
    stops: {
      origin: "Southeast Asia",
      cape: "Cape of Good Hope",
      dest: "Woolsthorpe",
    },
    stopNotes: {
      origin: "Origin",
      cape: "Around Africa",
      dest: "A destination that never was",
    },
  },
  disc: {
    kicker: "What he might have found instead",
    title: "If he lived, a new set of laws",
    hint: "Tap to open a law",
    finds: [
      {
        no: "I",
        title: "Conservation of odour",
        body: "Durian smell is never lost, only moved — and it falls off with the square of distance, like the force he never reached.",
        back: "I ∝ 1 / r² — close the door; it remains.",
      },
      {
        no: "II",
        title: "Point-force impact",
        body: "Thorns turn force into pressure: fracture mechanics, centuries early.",
        back: "P = F / A — A on a thorn is no place for a head.",
      },
      {
        no: "III",
        title: "The helmet",
        body: "The Royal Society’s first patent is not a reflecting telescope. It is something he should have had from the start.",
        back: "a = 0 beats a = g when the object has spikes.",
      },
      {
        no: "IV",
        title: "Universal repulsion",
        body: "Everyone within 50 metres moves away from the source of the smell — a reaction equal to the action.",
        back: "F_smell = −k / r² — all bodies recede equally.",
      },
    ],
  },
  close: {
    altFall: "Oil painting of Newton under a tree as a durian falls toward his head",
    altAfter: "Oil painting of Newton dazed after a durian strike, fruit split, garden reeking",
    before: "Before",
    after: "After",
    drag: "Drag to compare before and after",
    quote:
      "The apple taught us why the Moon never reaches the Earth. The durian taught us some things should never reach a head.",
    lede: "Gravity is unchanged. Apple and durian fall with the same g. The apple gives you a universe. The durian gives you a medical certificate.",
    note: "The apple story is a tale retold from Newton, not a lab note. The numbers here are rough estimates from typical fruit mass, a 4-metre drop, and a blunt impact-energy scale — not a medical report.",
  },
};

export const copy: Record<Locale, Copy> = { th, en };
